src/com/antares/cal/model/statistic/LongHaulDrives.java
package com.antares.cal.model.statistic;

/**
 * 
 * @author arved
 * object for the long haul driver statistic result query 
 */
public class LongHaulDrives {
	
	private String country;
	private long distance;
	
	public LongHaulDrives() {
		
	}
	
	public LongHaulDrives(String country, long distance) {
		this.country = country;
		this.distance = distance;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public long getDistance() {
		return distance;
	}

	public void setDistance(long distance) {
		this.distance = distance;
	}
	
}

src/com/antares/cal/model/user/PersonalData.java
package com.antares.cal.model.user;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;

/**
 * @author Fabian Mittmann
 */
@Embeddable
public class PersonalData {

    @Column(name = "first_name", nullable = false, length = 50)
    private String firstName;

    @Column(name = "last_name", nullable = false, length = 50)
    private String lastName;

    @Column(name = "gender", nullable = false, length = 20)
    @Enumerated(value = EnumType.STRING)
    private Gender gender;

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        if (firstName == null || firstName.trim().isEmpty()) {
            throw new IllegalArgumentException("cannot set a blank last name on PersonalData");
        }
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        if (lastName == null || lastName.trim().isEmpty()) {
            throw new IllegalArgumentException("cannot set a blank last name on PersonalData");
        }
        this.lastName = lastName;
    }

    public Gender getGender() {
        return gender;
    }

    public void setGender(Gender gender) {
        if (gender == null) throw new IllegalArgumentException("cannot unset the gender from PersonalData");
        this.gender = gender;
    }

    public String getFullName() {
        return getFirstName() + " " + getLastName();
    }

}

WebContent/gov/billing.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:b="http://bootsfaces.net/ui">
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
	<title>Rechnung</title>
</h:head>
<ui:include src="template.xhtml"></ui:include>
<h:body>
	<b:panel span="9">
		<h1>Rechnungen</h1>
		<br />
		<h:form>
			<b:panel look="primary" title="Rechnungspositionen" >
			<!-- Auswahl Rechnung aus dem Rechnungspool nach ID, Datum und Gesamtpreis und zeige über Knopf die Details an -->
						<b:dataTable value="#{invoiceController.allInvoices}" print="true" excel="true" var="invoice">
				<f:facet name="header">
								<tr>
								  <th>Fahrzeugbesitzer</th>
								  <th>Datum</th>
								  <th>Nettopreis</th>
								  <th>Steuern</th>
								  <th>Bezahlt?</th>
				
								</tr>
						    </f:facet>
				<b:dataTableColumn value="#{ownerUserController.getOwnerUserByID(invoice.ownerId).personalData.fullName}"></b:dataTableColumn>
				<b:dataTableColumn value="#{invoiceController.formatTimeStamp(invoice.invoiceDate)}"/>
				<b:dataTableColumn value="#{invoiceController.formatPrice(invoice.netAmount)}"> €</b:dataTableColumn>
				<b:dataTableColumn value="#{invoiceController.formatPrice(invoice.taxAmount)}"> €</b:dataTableColumn>
				<b:dataTableColumn value="#{invoiceController.formatIsPaid(invoice.isPaid())}"/>
			</b:dataTable>
			</b:panel>
		</h:form>
	</b:panel>
</h:body>

</html>

WebContent/gov/measurestationmanagement.xhtml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	  xmlns:ui="http://java.sun.com/jsf/facelets"
	  xmlns:h="http://java.sun.com/jsf/html"
	  xmlns:b="http://bootsfaces.net/ui">
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
	<title>Mautstationsverwaltung</title>
</h:head>
<ui:include src="template.xhtml"></ui:include>
<h:body>
	<b:panel span="9">
		<h1>Mautstationsverwaltung</h1>
		<b:panel title="Messstation" collapsible="false">
			<h:form>
				<b:panelGrid colSpans="6,6" size="sm">
					<b:button value="Messstation verwalten" style="width: 180px"
						      href="editmeasurestation.xhtml" look="primary" />
					<b:commandButton value="Messstation anlegen" style="width: 180px"
									 action="#{measureStationController.createMeasureStation}" look="success" />
				</b:panelGrid>
			</h:form>
		</b:panel>
		<br/>
		<!-- Route verwalten Container -->
		<b:panel title="Route" collapsible="false">
			<h:form>
				<b:panelGrid colSpans="6,6" size="sm">
					<b:button value="Routen verwalten" href="editdriveway.xhtml" style="width: 180px"
							  look="primary" />
					<b:commandButton value="Route anlegen" action="#{drivewayController.createDriveway}"
									 style="width: 180px" look="success" />
				</b:panelGrid>
			</h:form>
		</b:panel>
	</b:panel>
</h:body>

</html>

WebContent/gov/positiontracking.xhtml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:b="http://bootsfaces.net/ui"
	xmlns:g="http://openStreetMap.net/ui">

<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
	<title>Positionsermittlung</title>
</h:head>
<ui:include src="template.xhtml">
</ui:include>
<b:panel span="9">

	<h:body>
		<b:panel look="primary" title="Positionsermittlung">
		<h:form>
		
			<b:panelGrid columns="6">
				<h:outputText value="KFZ:" />
				<h:inputText value="Kennzeichen suchen"/>
				
				
				<input type="button" value="Jetzt ermitteln" onclick="showPanel();"/>
			</b:panelGrid>

			<br />
			<br />
			<br />
			
			<div id="loadingAll" style="display:none">
			<b:panel span="10">

				<b:panelGrid columns="2">
					<b:dateTimePicker label="Messung erfolgte um:" disabled = "true" value="08.11.2018 12:30:00" showIcon="false"
						readonly="true"> 
						</b:dateTimePicker>
					<b:inputText label="Die Folgende Messstation erfasste dabei die Daten:" value="Bautzen-Abfahrt 1"
						readonly="true"> 
						</b:inputText>
				</b:panelGrid>
				<b:image value="../static/data/img/GoogleMaps.JPG" width="750em" />
			</b:panel>
			</div>
			
			
			<script>

			function showImage(){
		        document.getElementById("loadingImage").style.visibility="hidden";
			}

			function showPanel(){
				document.getElementById("loadingAll").style.display="block";
			}

			</script>




		</h:form>
	</b:panel>
</h:body>
</b:panel>
</html>

WebContent/gov/statistics.xhtml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:b="http://bootsfaces.net/ui"
	xmlns:p="http://primefaces.org/ui">
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
	<title>Statistik</title>
</h:head>
<ui:include src="template.xhtml"></ui:include>
<h:body>
	<b:panel span="9">

		<h1>Statistikerstellung</h1>
		<br />
		<h:form>
			<b:panelGrid columns="2">
				<b:panel look="primary" title="Kilometerfresserstatistik erstellen" collapsible="false">
		        	<h:form>
			            <b:panelGrid columns="2">
			                <h:outputText value="Bitte geben Sie ein Anfangsdatum an:"/>
			                <b:datepicker mode="popup-icon" value="#{statisticController.startDate}"/>
			                <h:outputText value="Bitte geben Sie ein Enddatum an:"/>
			                <b:datepicker mode="popup-icon" value="#{statisticController.endDate}"/>
			                <b:commandButton action="#{statisticController.BuildLongHaulDriverStatistic()}" look="success"
			                                 value="Statistik erstellen"/>
			                <b:alert value="#{statisticController.warning}"/>
			            </b:panelGrid>
		        	</h:form>
				</b:panel>
			</b:panelGrid>
		</h:form>
	</b:panel>
</h:body>

</html>

WebContent/gov/template.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:b="http://bootsfaces.net/ui">

<!-- Header -->
<b:panel>
	<b:row>
		<b:column span="2">
			<b:image value="../static/data/img/CAL-Logo.png" width="100%" />
		</b:column>
		<b:column span="2"></b:column>
		<b:column span="7" style="margin-right:-4em">
			<b:image value="../static/data/img/grayCompanyLogo.png" width="60%" />
		</b:column>
		<b:column span="1" style="margin-left:2em">
			<!-- Logout Knopf-->
			<h:form>
				<b:commandButton action="#{logoutController.logout()}"
					value="Logout" size="lg" look="danger" style="margin-top:2em" />
			</h:form>
		</b:column>
	</b:row>
</b:panel>
<!-- Menuebar -->
<b:panel span="3">
	<ui:include src="menuGov.xhtml" />
</b:panel>

</html>